# Site settings
title: "Everton Strack - Desenvolvedor Front-End"
email: everton.strack@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Desenvolvedor Front-end e estudante de Design apaixonado por CSS e Javascript. Um pequeno apanhado sobre o dia-a-dia de um front-end, vida, o universo e tudo mais.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evertonstrack.com.br" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: evertonstrack
github_username:  evertonstrack
disqus_shortname: evertonstrack

# Where things are
source              : ./app
collections_dir     : collections
collections:
  posts:
    output: true
# plugins_dir         : ./app/plugins
# data_dir            : ./data
destination         : ./dist
layouts_dir         : layouts
includes_dir        : components

# Build settings
markdown: kramdown
google_analytics: UA-50129966-1
permalink: /blog/:title/
theme: minima
# plugins: [jekyll-feed]
lang: pt-br
locale: pt_BR
show_excerpts: false
gems:
  - jekyll-paginate-v2
  - jekyll-feed

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/:num/'
  title: ':title - Página :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Sobre
    url: /sobre
  - title: Blog
    url: /blog
  - title: Projetos
    url: /projetos

files_to_cache:
- '/assets/styles/all.css'
- '/assets/images/404.jpg'

pages_to_cache:
  - '/'
  - '/sobre/'
  - '/blog/'
  - '/projetos/'
  - '/404/'

# Include from processing.
include: ["_redirects",
          "_headers"]

# Exclude from processing.
exclude: [
  "components",
  "layouts",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "node_modules",
  "package.json",
  "package-lock.json",
  "gulpfile.js"
]
