name: Web Performance

on: [pull_request]

jobs:
  audit:
    name: Audit Performance on Netlify preview url
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
      - name: Wait for Netlify Deploy preview
        uses: JakePartusch/wait-for-netlify-action@v1.2
        id: wait-for-netflify-preview
        with:
          site_name: "evertonstrack"
          max_timeout: "120"
      - uses: actions/checkout@v1
      - name: Generate Lighthouse Report
        uses: justinribeiro/lighthouse-action@master
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ steps.wait-for-netflify-preview.outputs.url }}
          wptConnectionSpeed: threegfast
      - name: Saving Lighthouse Audit Artifacts
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-artifacts
          path: './results'
      - name: Lighthouse CI Audit
        run: |
            npm install -g @lhci/cli@0.6.x
            lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.wait-for-netflify-preview.outputs.url }} || echo "LHCI failed!"
            lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.wait-for-netflify-preview.outputs.url }}/sobre || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
